version: '3.8'

services:
  neo4j:
    image: neo4j:5.25-community
    container_name: neo4j-rag
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/knowledge123
      
      # Memory Configuration
      - NEO4J_server_memory_heap_initial_size=1G
      - NEO4J_server_memory_heap_max_size=2G
      - NEO4J_server_memory_pagecache_size=1G
      
      # Database Configuration
      - NEO4J_server_default_database=neo4j
      - NEO4J_server_default_listen_address=0.0.0.0
      
      # Performance Settings
      - NEO4J_server_bolt_listen_address=0.0.0.0:7687
      - NEO4J_server_http_listen_address=0.0.0.0:7474
      
      # Logging
      - NEO4J_server_logs_debug_level=INFO
      
      # Security (uncomment for production)
      # - NEO4J_server_bolt_tls_level=OPTIONAL
      # - NEO4J_server_https_enabled=true
      
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
        reservations:
          memory: 4G
          cpus: '1.0'
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p knowledge123 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  default:
    name: rag-network